### ISSUE TITLE
Unable to build on VS2019

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [mosra/magnum-bootstrap#18]
I've been trying to build a minimal program (branch: base) using these instructions 
https://github.com/mosra/magnum-bootstrap
https://doc.magnum.graphics/magnum/getting-started.html
but gotten stuck on errors posted below:

![image](https://user-images.githubusercontent.com/8407331/56466342-61f0b300-644b-11e9-9ae2-bf348df0b1bc.png)

This one goes away after removing constexpr qualifier. (should this be ignored?)

![image](https://user-images.githubusercontent.com/8407331/56466352-a11f0400-644b-11e9-8597-6efc974abea7.png)

I've tracked down the issue to MagnumGL project failing to build but still couldn't pinpoint the exact problem. What did I miss?

environment:
windows,
VS2019
clang (v142) (LLVM 8.0) 
Debug, x64
cmake setting:
WITH_SDL2APPLICATION=ON
set(CMAKE_CXX_STANDARD 17)

Corrade, magnum were installed as submodule.
both checked out @ tag 2019.01

**Comment by mosra** [comment]
> VS2019

Hi! Sorry to disappoint -- the codebase hasn't been tested against / adapted to VS 2019 yet and all the errors you're seeing are because of that. There is a *slight* chance things could start to work when you set `MSVC2017_COMPATIBILITY` to `ON` (it's a CMake option in Corrade), but I am not 100% betting on that -- so far, with every release of VS there were always new and exciting bugs to work around, so just applying the MSVC2017 workarounds to 2019 might not be enough.

I'll be definitely looking into this and ensuring things work correctly with VS 2019 but right now other things have a priority. Is there a chance you could run on VS 2017 in the meantime?

**Comment by UNDEFINED-BEHAVIOR** [comment]
The MSVC2017_COMPATIBILITY flag apparently works! (at least on this bootstrap/example program) It compiles now but for MSVC compiler only. I've noticed that similar but different error pops up when using llvm tool chain on both 2017 and 2019.

Is clang supported on windows? or am I supposed to use it through mingw?
if not then I'm going to close this ticket now.

**Comment by mosra** [comment]
Someone tried Clang support some time ago (see https://github.com/mosra/magnum/issues/227 and https://github.com/mosra/corrade/issues/40), but nothing was done since so I guess you'll run into problems there too. MinGW + GCC is known to be working, Clang on other platforms (Linux, macOS, iOS, Android...) is working as well, but frankly I have no idea how it behaves on Windows.

Leave the ticket open as a reminder for me to fix the VS2019 support ;)

**Comment by mosra** [comment]
MSVC 2019 support done with mosra/corrade@161c9e08363016531293fcc4d5c14fa9c00146e2, mosra/magnum@ddb16f6df810763b9f4e18dd585131ee24510e26, mosra/magnum@9e2a1117de6c2188331ea55990752ed5f5cd110a and mosra/magnum@d542e2b7e241f17470473c99e4140b8c8c7031ba. Other packages (plugins, extras, integration, examples) don't seem to need any adjustments so far.
