### ISSUE TITLE
Android Gradle build

### ISSUE THREAD

**Issue by janbajana** [mosra/magnum-bootstrap#21]
I want to build Magnum for Android and bootstrap projects and generate APK which I can install on my device.

It looks like I have built a minimal core magnum framework for Android including (corrade, magnum, magnum-integration with imguy). All using cmake setup here:
[cmake-scripts](https://github.com/janbajana/script-helpers/tree/master/cmake-scripts)
There are:
setup-corrade-build.sh
setup-magnum-build.sh
setup-magnum-integration-build.sh
I was following CI build scripts with some modifications to get it built.

Then I have magnum-bootstrap Gradle setup. I had to do some modifications to get it working, but there are errors. I am targetting Android 26, arm64-v8a.
I have built Magnum inside the "./library" folder in magnum-bootstrap project. Gradle config:
[magnum-bootstrap-android](https://github.com/janbajana/magnum-bootstrap-android/blob/master/build.gradle)

When I try to build gradle project I get the error during linking. Error log:
[Gradle error log](https://github.com/janbajana/magnum-bootstrap-android/blob/master/gradleLog.txt)

`../../../../libraries/lib/libMagnumAndroidApplication.a: error adding symbols: File in wrong format`

May it be some problem with target architecture?
`--target=aarch64-none-linux-android26`

Is my setup wrong? Any ideas?
Thank you.

**Comment by mosra** [comment]
Heh ... I don't know :)

Running `objdump` on the `libMagnumAndroidApplication.a` you have in the `lib/` dir of the bootstrap repository tells me it's `elf32-little`, while `*.a` libs I have built locally for AArch64 are `elf64-little`, so that's probably why it complains. Could it be that you changed the target architecture but somehow the built libraries still have 32-bit ARM (since that's what magnum's CI scripts target)?

**Comment by janbajana** [comment]
Yes, that is true. If I do `objdump -TC ./*.a | grep elf` I see also `elf32-little`. But I don't know why is that.
I set target `arm64-v8a`. How can I setup 64 build?

But if I remove from Gradle this line `Magnum::Application` but keep other Magnum files then I can build the project.

**Comment by mosra** [comment]
Interesting. Okay that's not the problem then (my knowledge of ELF internals is too weak to make anything out of that). 

A totally random idea -- I remember getting this error also due to `-fPIC` flag mismatches, can you try applying this patch, if it improves anything?

```patch
diff --git a/src/Magnum/Platform/CMakeLists.txt b/src/Magnum/Platform/CMakeLists.txt
index 6e73220f1..3ef3894c5 100644
--- a/src/Magnum/Platform/CMakeLists.txt
+++ b/src/Magnum/Platform/CMakeLists.txt
@@ -161,8 +161,8 @@ if(WITH_ANDROIDAPPLICATION)
     set_target_properties(MagnumAndroidApplication PROPERTIES
         DEBUG_POSTFIX "-d"
         FOLDER "Magnum/Platform")
-    # Assuming that PIC is not needed because the Application lib is always
-    # linked to the executable and not to any intermediate shared lib
+    # The application is always a *.so in the end, so we need PIC always.
+    set_target_properties(MagnumAndroidApplication PROPERTIES POSITION_INDEPENDENT_CODE ON)
     target_link_libraries(MagnumAndroidApplication PUBLIC
         MagnumGL
         android
```

I'm not sure why this wasn't ever a problem for me :thinking:

**Comment by janbajana** [comment]
I have found something. There are 2 possible CMAKE flags:
        `-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \`
        `-DANDROID_ABI=arm64-v8a \`

I had set up only `DCMAKE_ANDROID_ARCH_ABI=arm64-v8a` and it generates 32 bit. You have the same in your travis config.

I just added `-DANDROID_ABI` and it generated 2 output folders: `./lib` and './lib64'. Second folder has `elf64-little`.

Following CMake documentation should not matter which one you setup. It may be also an issue across CMake versions :).

**Comment by mosra** [comment]
If I understand correctly, the above patch didn't make any difference, right?

Didn't know about the two different cmake flags -- here it "just worked" using the former. What's your NDK and CMake version? Here I'm stuck on NDK r17 because of reasons listed in https://github.com/mosra/magnum/issues/310, and I won't try upgrading until the (supposedly fixed) CMake 3.16 is out.

**Comment by janbajana** [comment]
I did not try your path because DANDROID_ABI get it working.
I have updated my project here. This is the config:
https://github.com/janbajana/magnum-bootstrap-android/blob/master/build.gradle

In my project, I can build and generate .apk file and run it on my Android phone.

I am using the recent versions Android Studio provides: 
NDR version: 20.0.5594570
Target SDK API level: 26
Cmake: version '3.10.2'
buildToolsVersion "29.0.2"

**Comment by mosra** [comment]
Thanks for the version info. I assume this is related to the broken support of recent NDKs in CMake, not sure if there's anything to fix on Magnum side to be honest :) Once CMake 3.16 is out, I'll revisit this together with other things mentioned in mosra/magnum#310, but until then ... you're lucky you got it working at all :)
